#ifndef ANDROID_RPC_AUDIO_COMMON_H
#define ANDROID_RPC_AUDIO_COMMON_H

// method id for audio flinger
#define AF_METH_CREATE_TRACK 1
#define AF_METH_SAMPLE_RATE 2
#define AF_METH_FORMAT 3
#define AF_METH_FRAME_COUNT 4
#define AF_METH_LATENCY 5
#define AF_METH_SET_MASTER_VOLUME 6
#define AF_METH_SET_MASTER_MUTE 7
#define AF_METH_MASTER_VOLUME 8
#define AF_METH_MASTER_MUTE 9
#define AF_METH_SET_STREAM_VOLUME 10
#define AF_METH_SET_STREAM_MUTE 11
#define AF_METH_STREAM_VOLUME 12
#define AF_METH_STREAM_MUTE 13
#define AF_METH_SET_MODE 14
#define AF_METH_SET_MIC_MUTE 15
#define AF_METH_GET_MIC_MUTE 16
#define AF_METH_SET_PARAMETERS 17
#define AF_METH_GET_PARAMETERS 18
#define AF_METH_GET_INPUT_BUFFER_SIZE 19
#define AF_METH_INVALIDATE_STREAM 20
#define AF_METH_SET_VOICE_VOLUME 21
#define AF_METH_GET_INPUT_FRAMES_LOST 22
#define AF_METH_NEW_AUDIO_UNIQUE_ID 23
#define AF_METH_ACQUIRE_AUDIO_SESSION_ID 24
#define AF_METH_RELEASE_AUDIO_SESSION_ID 25
#define AF_METH_GET_PRIMARY_OUTPUT_SAMPLING_RATE 26
#define AF_METH_GET_PRIMARY_OUTPUT_FRAME_COUNT 27
#define AF_METH_SET_LOW_RAM_DEVICE 28
#define AF_METH_GET_RENDER_POSITION 29

// method id for track handle
#define TH_METH_DESTROY 1
#define TH_METH_START 2
#define TH_METH_STOP 3
#define TH_METH_FLUSH 4
#define TH_METH_PAUSE 5
#define TH_METH_ATTACH_AUX_EFFECT 6
#define TH_METH_SET_PARAMETERS 7
#define TH_METH_SIGNAL 8


#endif
